name: basic_cleaning
channels:
  - conda-forge
  - defaults
dependencies:
  - pandas=1.2.3
  - python=3.8
  - pip=20.3.3
  - pip:
      - wandb==0.10.31 #0.13.2 #0.12.17 #
      - protobuf==3.20.3 #femi
